# Generated by Django 4.1.4 on 2023-01-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issuing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        help_text="11 números sin guiones.",
                        max_length=20,
                        unique=True,
                        verbose_name="Número de CUIT",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre o Razón Social"
                    ),
                ),
                (
                    "iva_situation",
                    models.CharField(
                        choices=[
                            ("RM", "Responsable Monotributo"),
                            ("RI", "Responsable Inscripto"),
                            ("RNI", "Responsable No Inscripto"),
                            ("EX", "Exento"),
                            ("CF", "Consumidor Final"),
                        ],
                        max_length=100,
                        verbose_name="Situación frente al IVA",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Domicilio")),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de alta"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Emisor",
                "verbose_name_plural": "Emisores",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operario",
                "verbose_name_plural": "Operarios",
                "ordering": ("user",),
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Forma de pago",
                "verbose_name_plural": "Formas de pago",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descripción"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Normal"), (2, "Media"), (3, "Urgente")],
                        default=1,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "task_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "task_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de finalización"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Diaria"),
                            ("WEEKLY", "Semanal"),
                            ("MONTHLY", "Mensual"),
                            ("UNIQUE", "Única"),
                        ],
                        default="MONTHLY",
                        max_length=50,
                        verbose_name="Frecuencia",
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="Terminada"),
                ),
            ],
            options={
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
                "ordering": ("task_start_date",),
            },
        ),
    ]
