# Generated by Django 4.1.4 on 2023-01-11 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("income", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0001_initial"),
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="hiring",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="income.hiring",
                verbose_name="Contratación",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="configuration.operator",
                verbose_name="Operario",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="cuenta",
            field=models.OneToOneField(
                limit_choices_to={"subrubro__in": (1, 2, 4)},
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.cuenta",
                verbose_name="Cuenta contable",
            ),
        ),
        migrations.AddField(
            model_name="operator",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
    ]
