# Generated by Django 4.1.4 on 2023-01-11 22:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE_ORDER", "Orden de compra"),
                            ("INVOICE", "Factura"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de comprobante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprobante",
                "verbose_name_plural": "Comprobantes",
                "ordering": ("receipt_type",),
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identification_type",
                    models.CharField(
                        choices=[
                            ("CUIT", "CUIT"),
                            ("PASSPORT", "Pasaporte"),
                            ("DNI", "DNI"),
                            ("OTHER", "Otro"),
                        ],
                        default="CUIT",
                        max_length=50,
                        verbose_name="Tipo de identificación",
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        help_text="8 números sin puntos para DNI, 11 números sin guiones para CUIT/CUIL.",
                        max_length=11,
                        validators=[
                            main.models.validate_is_numeric,
                            django.core.validators.MinLengthValidator(
                                8,
                                "Asegúrese de que este valor sea mayor o igual a 8 caracteres.",
                            ),
                        ],
                        verbose_name="Número de identificación",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre o Razón Social"
                    ),
                ),
                (
                    "iva_situation",
                    models.CharField(
                        choices=[
                            ("RM", "Responsable Monotributo"),
                            ("RI", "Responsable Inscripto"),
                            ("RNI", "Responsable No Inscripto"),
                            ("EX", "Exento"),
                            ("CF", "Consumidor Final"),
                        ],
                        default="RI",
                        max_length=100,
                        verbose_name="Situación frente IVA",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=200, verbose_name="Domicilio fiscal"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Código de area sin 0 y número sin 15.",
                        max_length=10,
                        validators=[
                            main.models.validate_is_numeric,
                            django.core.validators.MinLengthValidator(
                                10,
                                "Asegúrese de que este valor sea igual a 10 caracteres.",
                            ),
                        ],
                        verbose_name="Número de teléfono",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Piso, número de departamento u otras aclaraciones.",
                        max_length=300,
                        null=True,
                        verbose_name="Notas",
                    ),
                ),
                (
                    "create_date",
                    models.DateField(auto_now_add=True, verbose_name="Fecha de alta"),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ("name",),
            },
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                fields=("identification_type", "identification_number"),
                name="supplier_uniqueness",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="expenses.supplier",
                verbose_name="Proveedor",
            ),
        ),
    ]
