from django.urls import include, path

from expenses import views

urlpatterns = [
    path(
        "supplier/",
        include(
            [
                path("list/", views.supplier_list_view, name="supplier_list"),
                path("create/", views.supplier_create_view, name="supplier_create"),
                path(
                    "update/<int:pk>/",
                    views.supplier_update_view,
                    name="supplier_update",
                ),
                path(
                    "detail/<int:pk>/",
                    views.supplier_detail_view,
                    name="supplier_detail",
                ),
            ]
        ),
    ),
    path(
        "expensesinvoice/",
        include(
            [
                path(
                    "list/",
                    views.expenses_invoice_list_view,
                    name="expensesinvoice_list",
                ),
                path(
                    "create/",
                    views.expenses_invoice_create_view,
                    name="expensesinvoice_create",
                ),
                path(
                    "detail/<int:pk>/",
                    views.expenses_invoice_detail_view,
                    name="expensesinvoice_detail",
                ),
                path(
                    "update/<int:pk>/",
                    views.expenses_invoice_update_view,
                    name="expensesinvoice_update",
                ),
            ]
        ),
    ),
    path(
        "expensespayment/",
        include(
            [
                path(
                    "list/",
                    views.payment_list_view,
                    name="expensespayment_list",
                ),
                path(
                    "create/",
                    views.payment_create_view,
                    name="expensespayment_create",
                ),
                path(
                    "detail/<int:pk>/",
                    views.payment_detail_view,
                    name="expensespayment_detail",
                ),
                path(
                    "update/<int:pk>/",
                    views.payment_update_view,
                    name="expensespayment_update",
                ),
            ]
        ),
    ),
    path(
        "expense/",
        include(
            [
                path(
                    "delete/<int:pk>/",
                    views.expense_delete_view,
                    name="expense_delete",
                ),
            ]
        ),
    ),
    path(
        "tax/",
        include(
            [
                path(
                    "delete/<int:pk>/",
                    views.tax_delete_view,
                    name="tax_delete",
                ),
            ]
        ),
    ),
]
