# Generated by Django 4.1.2 on 2022-12-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issuing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        help_text="11 números sin guiones.",
                        max_length=20,
                        unique=True,
                        verbose_name="Número de CUIT",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre o Razón Social"
                    ),
                ),
                (
                    "situacion_iva",
                    models.CharField(
                        choices=[
                            ("RM", "Responsable Monotributo"),
                            ("RI", "Responsable Inscripto"),
                            ("RNI", "Responsable No Inscripto"),
                            ("EXC", "Excento"),
                            ("CF", "Consumidor Final"),
                        ],
                        max_length=100,
                        verbose_name="Situación frente al IVA",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Domicilio")),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de alta"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Emisor",
                "verbose_name_plural": "Emisores",
                "ordering": ("name",),
            },
        ),
    ]
