# Generated by Django 4.1.2 on 2022-12-05 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Descripción",
                        max_length=300,
                        null=True,
                        verbose_name="Notas",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "reference_code",
                    models.CharField(
                        help_text="Código único de indentificación del producto. Máximo 20 caracteres.",
                        max_length=20,
                        unique=True,
                        verbose_name="Código de referencia",
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(
                        choices=[
                            ("SERVICE", "Servicio"),
                            ("UNIT", "Unidad"),
                            ("KILOGRAM", "Kilogramo"),
                            ("GRAM", "Gramo"),
                            ("METER", "Metro"),
                            ("SQUARE METER", "Metro cuadrado"),
                            ("CUBIC METER", "Metro cúbico"),
                            ("LITER", "Litro"),
                            ("MILLILITER", "Mililitro"),
                        ],
                        default="SERVICE",
                        max_length=20,
                        verbose_name="Unidad de medida",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción.",
                        max_length=300,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="products",
                        to="inventory.category",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        limit_choices_to={"subrubro": 29},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="products",
                        to="accounting.cuenta",
                        verbose_name="Cuenta contable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de producto",
                "verbose_name_plural": "Tipos de producto",
                "ordering": ("-change_date",),
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                ("address", models.CharField(max_length=200, verbose_name="Domicilio")),
                ("location", models.CharField(max_length=50, verbose_name="Ubicación")),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Piso, número de departamento u otras aclaraciones.",
                        max_length=300,
                        null=True,
                        verbose_name="Notas",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Depósito",
                "verbose_name_plural": "Depósitos",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        default=0, max_length=20, verbose_name="Cantidad"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        limit_choices_to={"subrubro": 10},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="stocks",
                        to="accounting.cuenta",
                        verbose_name="Cuenta de inventario",
                    ),
                ),
                (
                    "producttype",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="stocks",
                        to="inventory.producttype",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="stocks",
                        to="inventory.warehouse",
                        verbose_name="Depósito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
                "ordering": ("producttype", "warehouse", "amount"),
            },
        ),
    ]
