# Generated by Django 4.1.4 on 2023-01-11 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                ("address", models.CharField(max_length=200, verbose_name="Domicilio")),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Piso, número de departamento u otras aclaraciones.",
                        max_length=300,
                        null=True,
                        verbose_name="Notas",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Depósito",
                "verbose_name_plural": "Depósitos",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=200, verbose_name="Producto")),
                (
                    "amount",
                    models.PositiveIntegerField(default=0, verbose_name="Cantidad"),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        default=7,
                        limit_choices_to={"subrubro": 9},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock",
                        to="accounting.cuenta",
                        verbose_name="Cuenta de inventario",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock",
                        to="inventory.warehouse",
                        verbose_name="Depósito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stock",
                "ordering": ("product", "warehouse", "amount"),
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descripción"),
                ),
                (
                    "reference_code",
                    models.CharField(
                        help_text="Código único de identificación del producto. Máximo 20 caracteres.",
                        max_length=20,
                        unique=True,
                        verbose_name="Código de referencia",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        default=15,
                        limit_choices_to={"subrubro": 28},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_type",
                        to="accounting.cuenta",
                        verbose_name="Cuenta de ventas",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_type",
                        to="inventory.stock",
                        verbose_name="Stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de servicio",
                "verbose_name_plural": "Tipos de servicio",
            },
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                fields=("product", "warehouse"), name="stock_uniqueness"
            ),
        ),
    ]
