# Generated by Django 4.1.4 on 2023-01-11 22:55

import datetime

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("accounting", "0001_initial"),
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Domicilio"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Código de area sin 0 y número sin 15.",
                        max_length=10,
                        validators=[
                            main.models.validate_is_numeric,
                            django.core.validators.MinLengthValidator(
                                10,
                                "Asegúrese de que este valor sea igual a 10 caracteres.",
                            ),
                        ],
                        verbose_name="Número de teléfono",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="Notas"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Ubicación"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        default=datetime.date(2023, 1, 26),
                        verbose_name="Fecha de vencimiento",
                    ),
                ),
                (
                    "sale_term",
                    models.CharField(
                        choices=[
                            ("CASH", "Contado"),
                            ("TERM15", "A plazo - 15 días"),
                            ("TERM30", "A plazo - 30 días"),
                            ("TERM60", "A plazo - 60 días"),
                            ("OTHER", "Otro"),
                        ],
                        default="CASH",
                        max_length=50,
                        verbose_name="Plazo de venta",
                    ),
                ),
                (
                    "subtotal",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Asegúrese de que este valor sea mayor o igual a 0."
                            )
                        ],
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "total",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Asegúrese de que este valor sea mayor o igual a 0."
                            )
                        ],
                        verbose_name="Total",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identification_type",
                    models.CharField(
                        choices=[
                            ("CUIT", "CUIT"),
                            ("PASSPORT", "Pasaporte"),
                            ("DNI", "DNI"),
                            ("OTHER", "Otro"),
                        ],
                        default="CUIT",
                        max_length=50,
                        verbose_name="Tipo de identificación",
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        help_text="8 números sin puntos para DNI, 11 números sin guiones para CUIT/CUIL.",
                        max_length=11,
                        validators=[
                            main.models.validate_is_numeric,
                            django.core.validators.MinLengthValidator(
                                8,
                                "Asegúrese de que este valor sea mayor o igual a 8 caracteres.",
                            ),
                        ],
                        verbose_name="Número de identificación",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre o Razón Social"
                    ),
                ),
                (
                    "iva_situation",
                    models.CharField(
                        choices=[
                            ("RM", "Responsable Monotributo"),
                            ("RI", "Responsable Inscripto"),
                            ("RNI", "Responsable No Inscripto"),
                            ("EX", "Exento"),
                            ("CF", "Consumidor Final"),
                        ],
                        default="RI",
                        max_length=100,
                        verbose_name="Situación frente IVA",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=200, verbose_name="Domicilio fiscal"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Código de area sin 0 y número sin 15.",
                        max_length=10,
                        validators=[
                            main.models.validate_is_numeric,
                            django.core.validators.MinLengthValidator(
                                10,
                                "Asegúrese de que este valor sea igual a 10 caracteres.",
                            ),
                        ],
                        verbose_name="Número de teléfono",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Piso, número de departamento u otras aclaraciones.",
                        max_length=300,
                        null=True,
                        verbose_name="Notas",
                    ),
                ),
                (
                    "create_date",
                    models.DateField(auto_now_add=True, verbose_name="Fecha de alta"),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "cuenta_activo",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"subrubro__rubro__capitulo": "Activo"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_activo",
                        to="accounting.cuenta",
                        verbose_name="Cuenta activo",
                    ),
                ),
                (
                    "cuenta_pasivo",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"subrubro__rubro__capitulo": "Pasivo"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_pasivo",
                        to="accounting.cuenta",
                        verbose_name="Cuenta pasivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="Hiring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Domicilio"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Código de area sin 0 y número sin 15.",
                        max_length=10,
                        validators=[
                            main.models.validate_is_numeric,
                            django.core.validators.MinLengthValidator(
                                10,
                                "Asegúrese de que este valor sea igual a 10 caracteres.",
                            ),
                        ],
                        verbose_name="Número de teléfono",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="Notas"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Ubicación"
                    ),
                ),
                (
                    "is_placed",
                    models.BooleanField(default=False, verbose_name="Colocado"),
                ),
                ("is_clean", models.BooleanField(default=True, verbose_name="Limpio")),
                (
                    "start_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        default=datetime.date(2023, 1, 26),
                        verbose_name="Fecha de finalización",
                    ),
                ),
                (
                    "budget",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"hiring__isnull": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="income.budget",
                        verbose_name="Presupuesto",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hiring",
                        to="income.customer",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contratación",
                "verbose_name_plural": "Contrataciones",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Domicilio"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Código de area sin 0 y número sin 15.",
                        max_length=10,
                        validators=[
                            main.models.validate_is_numeric,
                            django.core.validators.MinLengthValidator(
                                10,
                                "Asegúrese de que este valor sea igual a 10 caracteres.",
                            ),
                        ],
                        verbose_name="Número de teléfono",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="Notas"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Ubicación"
                    ),
                ),
                (
                    "cai",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número de CAI",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Pagada")),
                (
                    "has_electronic_invoice",
                    models.BooleanField(
                        default=False, verbose_name="Tiene factura electrónica"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        default=datetime.date(2023, 1, 26),
                        verbose_name="Fecha de vencimiento",
                    ),
                ),
                (
                    "sale_term",
                    models.CharField(
                        choices=[
                            ("CASH", "Contado"),
                            ("TERM15", "A plazo - 15 días"),
                            ("TERM30", "A plazo - 30 días"),
                            ("TERM60", "A plazo - 60 días"),
                            ("OTHER", "Otro"),
                        ],
                        default="CASH",
                        max_length=50,
                        verbose_name="Plazo de venta",
                    ),
                ),
                (
                    "subtotal",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Asegúrese de que este valor sea mayor o igual a 0."
                            )
                        ],
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "total",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Asegúrese de que este valor sea mayor o igual a 0."
                            )
                        ],
                        verbose_name="Total",
                    ),
                ),
                (
                    "asiento",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.asiento",
                        verbose_name="Asiento",
                    ),
                ),
                (
                    "budget",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"invoice__isnull": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="income.budget",
                        verbose_name="Presupuesto",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="income.customer",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_subtotal",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Asegúrese de que este valor sea mayor o igual a 0."
                            )
                        ],
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="income.budget",
                        verbose_name="Presupuesto",
                    ),
                ),
                (
                    "hiring",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="income.hiring",
                        verbose_name="Contratación",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="income.invoice",
                        verbose_name="Facturas",
                    ),
                ),
                (
                    "tax_type",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="taxes",
                        to="accounting.taxtype",
                        verbose_name="Tipo de impuesto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impuesto",
                "verbose_name_plural": "Impuestos",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(default=0, verbose_name="Cantidad"),
                ),
                (
                    "unitario",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Asegúrese de que este valor sea mayor o igual a 0."
                            )
                        ],
                        verbose_name="Unitario",
                    ),
                ),
                (
                    "service_subtotal",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Asegúrese de que este valor sea mayor o igual a 0."
                            )
                        ],
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="income.budget",
                        verbose_name="Presupuesto",
                    ),
                ),
                (
                    "hiring",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="income.hiring",
                        verbose_name="Contratación",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="income.invoice",
                        verbose_name="Facturas",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="inventory.servicetype",
                        verbose_name="Tipo de servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
            },
        ),
        migrations.CreateModel(
            name="IncomePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administración"),
                            ("MARIANO", "Mariano"),
                            ("OPERATOR", "Operario"),
                        ],
                        max_length=50,
                        verbose_name="Cobrador",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="Monto")),
                (
                    "issue_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="income_payments",
                        to="income.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_paid": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="income_payments",
                        to="income.invoice",
                        verbose_name="Factura",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="configuration.paymentmethod",
                        verbose_name="Forma de pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cobro",
                "verbose_name_plural": "Cobros",
                "ordering": ("issue_date",),
            },
        ),
        migrations.AddField(
            model_name="budget",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="income.customer",
                verbose_name="Cliente",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("identification_type", "identification_number"),
                name="customer_uniqueness",
            ),
        ),
    ]
