# Generated by Django 4.1.2 on 2022-12-05 04:04

import datetime

import django.db.models.deletion
from django.db import migrations, models

import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identification_type",
                    models.CharField(
                        choices=[
                            ("CUIT", "CUIT"),
                            ("PASSPORT", "Pasaporte"),
                            ("DNI", "DNI"),
                            ("OTHER", "Otro"),
                        ],
                        default="CUIT",
                        max_length=50,
                        verbose_name="Tipo de identificación",
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        help_text="8 números sin puntos para DNI, 11 números sin guiones para CUIT/CUIL",
                        max_length=20,
                        verbose_name="Número de identificación",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre o Razón Social"
                    ),
                ),
                (
                    "situacion_iva",
                    models.CharField(
                        choices=[
                            ("RM", "Responsable Monotributo"),
                            ("RI", "Responsable Inscripto"),
                            ("RNI", "Responsable No Inscripto"),
                            ("EXC", "Excento"),
                            ("CF", "Consumidor Final"),
                        ],
                        default="RI",
                        max_length=100,
                        verbose_name="Situación frente IVA",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Domicilio")),
                ("location", models.CharField(max_length=50, verbose_name="Ubicación")),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Código de area sin 0 y número sin 15.",
                        max_length=10,
                        validators=[main.models.validate_phone_number],
                        verbose_name="Número de teléfono",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Piso, número de departamento u otras aclaraciones.",
                        max_length=300,
                        null=True,
                        verbose_name="Notas",
                    ),
                ),
                (
                    "create_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha de alta"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "cuenta",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="accounting.cuenta",
                        verbose_name="Cuenta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha de emisión"
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Domicilio")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Ubicación"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Código de area sin 0 y número sin 15.",
                        max_length=10,
                        validators=[main.models.validate_phone_number],
                        verbose_name="Número de teléfono",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        default=datetime.date(2022, 12, 20),
                        verbose_name="Fecha de vencimiento",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="Notas"
                    ),
                ),
                (
                    "cai",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número de CAI",
                    ),
                ),
                (
                    "sale_term",
                    models.CharField(
                        choices=[
                            ("CASH", "Contado"),
                            ("TERM15", "A plazo - 15 días"),
                            ("TERM30", "A plazo - 30 días"),
                            ("TERM60", "A plazo - 60 días"),
                            ("OTHER", "Otro"),
                        ],
                        default="CASH",
                        max_length=50,
                        verbose_name="Plazo de venta",
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("subtotal", models.FloatField(default=0, verbose_name="Subtotal")),
                ("total", models.FloatField(default=0, verbose_name="Total")),
                (
                    "receipt_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tipo de comprobante"
                    ),
                ),
                (
                    "has_electronic_invoice",
                    models.BooleanField(
                        default=False, verbose_name="Tiene factura electrónica"
                    ),
                ),
                (
                    "is_placed",
                    models.BooleanField(default=False, verbose_name="Colocado"),
                ),
                ("is_clean", models.BooleanField(default=True, verbose_name="Limpio")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="receipts",
                        to="income.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "has_hiring",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="budget",
                        to="income.receipt",
                        verbose_name="Tiene contratación",
                    ),
                ),
                (
                    "has_invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="hiring",
                        to="income.receipt",
                        verbose_name="Tiene factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprobante",
                "verbose_name_plural": "Comprobantes",
                "ordering": ("issue_date",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtotal", models.FloatField(default=0, verbose_name="Subtotal")),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="taxes",
                        to="income.receipt",
                        verbose_name="Comprobante",
                    ),
                ),
                (
                    "tax_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="taxes",
                        to="accounting.taxtype",
                        verbose_name="Tipo de impuesto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impuesto",
                "verbose_name_plural": "Impuestos",
                "ordering": ("tax_type",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(default=0, verbose_name="Cantidad")),
                ("unitario", models.FloatField(default=0, verbose_name="Unitario")),
                ("subtotal", models.FloatField(default=0, verbose_name="Subtotal")),
                (
                    "product_type",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="products",
                        to="inventory.producttype",
                        verbose_name="Tipo de producto",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="products",
                        to="income.receipt",
                        verbose_name="Comprobante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ("product_type",),
            },
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("identification_type", "identification_number"),
                name="customer_uniqueness",
            ),
        ),
    ]
