# Generated by Django 4.1.2 on 2022-12-05 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rubro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capitulo",
                    models.CharField(
                        choices=[
                            ("Activo", "Activo"),
                            ("Pasivo", "Pasivo"),
                            ("Patrimonio", "Patrimonio"),
                            ("Ingresos", "Ingresos"),
                            ("Egresos", "Egresos"),
                        ],
                        max_length=50,
                        verbose_name="Capítulo",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Rubro",
                "verbose_name_plural": "Rubros",
            },
        ),
        migrations.CreateModel(
            name="TaxType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                ("percentage", models.FloatField(verbose_name="Porcentaje")),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de impuesto",
                "verbose_name_plural": "Tipos de impuesto",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Subrubro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "rubro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="subrubros",
                        to="accounting.rubro",
                        verbose_name="Rubro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("debe", models.FloatField(default=0, verbose_name="Debe")),
                ("haber", models.FloatField(default=0, verbose_name="Haber")),
                (
                    "subrubro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="cuentas",
                        to="accounting.subrubro",
                        verbose_name="Subrubro",
                    ),
                ),
            ],
        ),
    ]
